In [1]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder
df=pd.DataFrame({'colors':
                 ["red","blue","green","orange","yellow","black"]})
print(df.head())

   colors
0     red
1    blue
2   green
3  orange
4  yellow


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Create an object of OneHotEncoder
encoder = OneHotEncoder()

# Apply fit_transform
encoded = encoder.fit_transform(df[['colors']]).toarray()
#this would create an sparx matrix

print(encoded)


[[0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]


TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid